buttplugio/buttplug

buttplug/dependencies/buttplug-device-config/buttplug-device-config.json
buttplug/dependencies/buttplug-device-config/buttplug-device-config.yml

The device configuration has been missing before, so whenever a Onyx+ has been
detected, it has been ignored as the device configuration could not be found.
This should fix #160

device-config: add configuration for Onyx+

---

buttplug/dependencies/buttplug-device-config/buttplug-device-config.json
buttplug/dependencies/buttplug-device-config/buttplug-device-config.yml

Config only change to get support for the mission.
Note that when not set to vibrate, the depth sensor will control the speed.

feat: Add Lovense Mission to config

---

buttplug/dependencies/buttplug-device-config/buttplug-device-config.json
buttplug/dependencies/buttplug-device-config/buttplug-device-config.yml

Turns out that buttplug-rs's device config is 5 commits
ahead of the device config repo and 1 behind. It might
be possible to do the subtree merge thing to pull these
in order, but the manual merge was trivial to bring over
the one missing change:
A few WeVibe devices were listed under the wevibe protocol
where they really needed to be listed under wevibe-8bit:
- Chorus
- Melt
- Wand
The Libo Feather also made its way into the config in that
change.

chore: Manually merging 3fb841bc from device-config repo

---

buttplug/src/util/future.rs

Hello :crab:,
I had previously suggested a fix to the `Send/Sync` impl of `ButtplugFutureStateShared` in #225,
and the fix was made in https://github.com/buttplugio/buttplug-rs/commit/3199bd8623d05341b4047f53e143ae67d7d9f064 .
However @Qwaz pointed out in https://github.com/buttplugio/buttplug-rs/issues/225#issuecomment-751514747 that
part of the suggestion I had made was incorrect, and this PR is to make a follow-up fix.
After the fix, the requirement for `ButtplugFutureStateShared<T>` to be `Sync` becomes `T: Send` instead of `T: Sync`.
(via auto trait implementations)
Sorry for the mistake I made in my previous suggestion,
and thank you for reviewing this PR :+1:

ButtplugFutureStateShared: fix send/sync impl

---

buttplug/buttplug-device-config/buttplug-device-config.json
buttplug/buttplug-device-config/buttplug-device-config.yml
buttplug/src/device/protocol/libo_elle.rs
buttplug/src/device/protocol/libo_shark.rs
buttplug/src/device/protocol/libo_vibes.rs
buttplug/src/device/protocol/mod.rs

This PR includes each of the 3 Libo Protocols (1 commit each).
Tests passed locally and with all applicable devices.
The LiboShark protocol skips the futures array, since it only one characteristic, the other 2 protocols follow the pattern used in other multi-characteristic protocols.
~~The LiboVibes protocol needs to know the number of vibrators, which I'm fetching from the message_attributes, but I suspect there's a better way to get that value (I'll update that logic pending feedback).~~ Answered my own question: `cmds.len()` is the vibration count.

Libo support

---

buttplug/buttplug-device-config/buttplug-device-config.json
buttplug/buttplug-device-config/buttplug-device-config.yml
buttplug/src/device/protocol/kiiroo_v21_initialized.rs
buttplug/src/device/protocol/mod.rs

We know that the linear devices will accept the initialization without
any obious side-effects, whether needed or not.
The vibes on the otherhand will at best start up at 100% speed
or refuse all commands at worse.
I've left the vibration and linear logic in both protocols, so if
we've got a device in the wrong category, it's just a config change
to fix in the future.
Fixes #281

fix: Splitting kiiroo_v21 for devices that need initailization

---

buttplug/buttplug-device-config/buttplug-device-config.json
buttplug/buttplug-device-config/buttplug-device-config.yml
buttplug/src/device/protocol/jejoue.rs
buttplug/src/device/protocol/mod.rs

Only tested with the Dua.
Since this device takes 1 speed for neither or both motors,
the first vibe speed is used to control both motors. If only
1 of the 2 vibes has non-zero speeds, that vibe will run at
the requested speed.

feat: Adding support for Je Joue Nuo and Dua

---

buttplug/src/connector/transport/websocket/websocket_client.rs

This fixes an issue with intiface where on some client disconnects the websocket would get stuck open and would require server restart to allow further connections.

fix: Writer not closing after connector holding websocket is dropped

---

buttplug/buttplug-device-config/buttplug-device-config.json
buttplug/buttplug-device-config/buttplug-device-config.yml

This reuses the prior Svakom protocol, mapping in the
new BLE names (from data privide in #325).
Tested with original Ella and Vick Neo.

feat: Support Svakom Neo Vibes

---

buttplug/buttplug-device-config/buttplug-device-config.json
buttplug/buttplug-device-config/buttplug-device-config.yml
buttplug/src/device/protocol/vorze_sa.rs

Is there a typo in that vendor name? Nope... it really is festa...
https://www.afesta.tv/gekisin/index2.html
As we know, Vorze products are always a little awkward due
to the device type being required in the control messages
(the Rocket+1D is 0x07), but this device was extra awkward
as it required writeWithResponse messages too.

feat: Adding support for Adult Festa Rocket+1D

---

buttplug/buttplug-device-config/buttplug-device-config.json
buttplug/buttplug-device-config/buttplug-device-config.yml
buttplug/src/device/mod.rs
buttplug/src/device/protocol/vibratissimo.rs

This change uses the device model name to identify the
type of Vibratissimo device, allowing 2 or 3 actuator
devices to be properly controlled

feat: Better Vibratissimo support

---

buttplug/buttplug-device-config/buttplug-device-config.json
buttplug/buttplug-device-config/buttplug-device-config.yml

Adding the Lovense Blast identifier and UUIDs
Adding the Lovense Edge2 paired UUIDs
Adding the BatteryCmd to the non-default Lovense devices
Adding the Dolp identifier to the Lovense dongle config

feat: More Lovense device config

---

buttplug/src/device/protocol/wevibe.rs
buttplug/src/device/protocol/wevibe8bit.rs

It seems BlueZ is more picky than Web Bluetooth about this.
Tested with the Pivot. @blackspherefollower confirmed this works with the Gala.

fix: Use write with response for We-Vibe devices

---

buttplug/buttplug-device-config/buttplug-device-config-schema.json
buttplug/buttplug-device-config/buttplug-device-config.json
buttplug/buttplug-device-config/buttplug-device-config.yml
buttplug/src/device/configuration_manager.rs
buttplug/src/device/mod.rs
buttplug/src/device/protocol/magic_motion_v4.rs
buttplug/src/device/protocol/mod.rs
buttplug/src/server/comm_managers/btleplug/btleplug_device_impl.rs
buttplug/src/server/device_manager_event_loop.rs

I've broken the change up into distinct pieces so it's clearer what's related to what and why I had to make the changes.
* The first commit allows multiple matching protocols for a device to be iterated over to find the right match.
* The second commit allows a potentially matching protocol to be skipped if the device lacks a required endpoint
* The third change allows for a device previously connected to be re-connected
The overall change requires https://github.com/deviceplug/btleplug/pull/247 as my MagicMotion devices consistently
failed to find the Tx characteristic and because if the advertised services had been received without the BLE name, then
we never get enough advertising data to make the correct match until we release the connection.
Fixes #426

fix: Issue #426

---

spec/protocol-spec/enumeration.md

Fixes #489 by removing the `StepRange` field from the example and converting it to a `StepCount` field.
This approach was prefered as `ScalarCmd` and the rest of types of messages that accept these device arguments expect a 0.0-1.0 double as the argument, so having the real range doesn't provide a real value while the `StepCount` does unless those messages offer a way to use the devices real range.

[Protocol spec] Remove StepRange from Device List message example

---

spec/protocol-spec/sensors.md

Example for `SensorReadCmd` uses a string as `SensorIndex` when it should be an integer.

Fix SensorIndex type

---

buttplug/src/server/device/hardware/communication/lovense_connect_service/lovense_connect_service_hardware.rs

What:
Patched "lovense service device connection check loop" in lovense_connect_service_hardware.rs.
Why:
The connection check loop had no delay and would cause a DOS condition for the desktop Lovense Connect app in release builds of the library. The DOS condition would not happen in debug builds likely due to speed reasons.

Patched an issue with Lovense Connect connection issues.

---

buttplug/src/core/connector/transport/pipe/pipe_client.rs
buttplug/src/core/connector/transport/pipe/pipe_server.rs

See #537
With this the example now works as expected and does not spin forever.
This seems to be the intended way and not break anything, tho I'm a bit unsettled by the fact that the part where the error arose seems to be pretty foundational, and I have no explanation as to why this went unnoticed for *looks at git blame * ... a year?

fix: Do not abort in pipe_connector when UnixStream is not ready yet

---

build/vcpkg_x64-windows.txt
buttplug/Cargo.toml
buttplug/src/core/connector/transport/websocket/websocket_client.rs

Fixes #575.
Replaces it with [rustls](https://github.com/rustls/rustls) so we don't need any external libraries anymore. This just removes it right now and some local checking with [cargo-why](https://github.com/boringcactus/cargo-why) says it's gone, but it could come back in the future. [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) could be used to check against that.
Note the [rustls-native-certs](https://github.com/rustls/rustls-native-certs#readme) bit still uses [openssl-probe](https://github.com/alexcrichton/openssl-probe) to find certificates on Linux machines, which technically wants OpenSSL installed, but doesn't require any of the libraries to be installed, only the certs (and not even that on non-Linux machines).

Remove openssl

---

buttplug/README.md

Fixed typos, capitalization of some words, and the wording of the Contributing section in the main crate README.md file.

doc: Fix typos and capitalization in crate README.md

---

buttplug/Cargo.toml
buttplug/src/core/connector/transport/websocket/websocket_client.rs

Follow up to https://github.com/buttplugio/buttplug/pull/576 and maybe properly fixing #575.
tokio-native-tls gets pulled in by intiface-central, which activates the code at https://github.com/sdroege/async-tungstenite/blob/c4fb3afb8a94f2c89508c45bbd09215097b315bc/src/tokio.rs#L65 and then the `connect_async_with_tls_connector` signature changes. Yay. This version redoes things with `tokio-native-tls` and compiles cleanly with intiface-central.

Use tokio_native_tls for intiface compatibiity

---

buttplug/src/server/device/protocol/mizzzee_v3.rs

When I was washing myself, when I was in the toilet, the thought often occurred to me: "Maybe to_be_bytes does not mean 'to_be bytes', but 'to BE bytes' - Big Endian, and there's 'to_le_bytes' method as well?". It turned out to be true.
I finally remembered this while I was in a suitable place - at the computer.
Now this thought will not torment me in the bathroom.

chore: Replace use of BE bytes and swap combination with LE bytes

---

buttplug/Cargo.toml

Tested with a Nintendo Joy-Con on aarch64-darwin.
Configuration issue from an erroneous copy-paste (unfortunately I can't test HID on Linux, but if it's still broken it might be a trivial fix).
I also don't have a physical Windows device to test it on, but I'm assuming the `windows_native` feature should be enabled... I'd appreciate someone testing to make sure HID on Windows still works.

Fix HID support on macOS
