buttplugio/buttplug

buttplug/src/device/protocol/youou.rs
The Youou devices have names like VX001_01234, where the numbers
after the _ are variable. To cope with this in the configuration
file, the protocol is matched using the wildcarded name VX001_*
When the default identifier lookup comes in though, it looks for
VX001_01234 which doesn't exist.
This change forces the identifier lookup to VX001_
An alternative but far larger change could be to have
DeviceConfigurationManager::find_configuration() report on the
identifier that was actually matched to see if wildcards were involved.
This would require changing the whole PartialEq implementation for
DeviceSpecifier, which given BLE names are not the only specifier
type that needs to be considered, didn't look like the right direction
whilst this issue only affects a small number of BLE protocols.
=> bug: Youou wildcard prevents identifier from being found

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml, buttplug/buttplug-device-config/package-lock.json
The models currently available to buy do appear to follow
the weird traits of the Onyx+:
- Connecting new systems requires the power button to be held
for 15 seconds before the blue light flashes rapidly for a
few seconds.
- On Windows, the Rey immediatly disconnects on first write
unless you have previously connected to the Rey using the
Windows Settings Bluetooth devices panel (power cycle the
Rey to make it discoverable again).
=> feat: Remapping in Realm Rey as a Kiiroo Onyx 2.1/+

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml, buttplug/src/device/protocol/prettylove.rs
Another protocol with wildcard matching that casues panics when
the name isn't matched by any identifier.
Encountered testing the Archenemy (working as expected with the fix)
=> fix: Correct PrettyLove wildcard handling

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml
This should add suport for the Dolp (Lush clone).
Untested, but conforms to the information provided via Discord
and what's visible inside the Dolp SDK.
=> feat: Loveai Dolp support

buttplug/src/device/protocol/lovense.rs
For some reason the initial delay+timeout wasn't enough to satisty
at least one of the Lovense protocol clone devices.
This change creates a loop around the write/wait for read so that
if we don't get a response, we'll ask again.
Fixes: #277
=> fix: Using a retry loop in the Lovense DeviceInfo read

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml
These are both clones of the MagicMotion Smart Kegel
=> feat: Support for Gballs2 and Femometer Lilac

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml, buttplug/src/device/protocol/cachito.rs, buttplug/src/device/protocol/mod.rs
Both have heavy solenoid based thrusting oscillators.
The Tao has a suction oscillator
The Ice Cream has a vibration motor.
=> feat: Adding support for 2 Cachito devices

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml, buttplug/src/device/protocol/mod.rs, buttplug/src/device/protocol/patoo.rs
Tested with the 3 Patoo devices I've got.
There may be another to be added later.
=> feat: Adding Patoo device support

buttplug/src/device/protocol/vorze_sa.rs
Add support for the vorze A10 piston, including pretty good timing.
=> Issue #348

buttplug/src/device/protocol/vorze_sa.rs
This fixes #353
Also added a test for the VorzePiston after correcting the
speed limit to 100. Sending >100 speed does seem to work,
but appears to run at the max speed of 100 regardless.
The piston logic doesn't handle incomplete moves (a movement
requested whilst the previous movement is still in progress)
so as a precaution, if told to move to the same location the
piston will do so at full speed rather than 0.
=> fix: Using write with response on all Vorze devices

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml, buttplug/src/device/protocol/mod.rs, buttplug/src/device/protocol/zalo.rs
Tested with the Jeanne and Queen, and added config for the King
based on prior anaysis by @TheHardew
Other Zalo devices will require config updates as they appear.
=> feat: Adding support for Zalo devices

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml, buttplug/src/device/protocol/fredorch.rs, buttplug/src/device/protocol/mod.rs
I have not worked out the timings for this device yet, and have
continued the anti-pattern of using the fleshlight speed conversion
scaled for the Fredorch's limits.
I'll revisit the timings once I've completed the timing capture
automation I'm working on for the Vorze Piston.
=> feat: Support the Fredorch F21S Fucking Machine

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml, buttplug/src/device/protocol/mod.rs, buttplug/src/device/protocol/svakom_alex.rs, buttplug/src/device/protocol/svakom_sam.rs
The Sam has a vibe and an air bladder cycling thing, which
made more sense to support as on/off than not.
The Alex is technically an Oscillator, but again, it makes
more sense to support it as a vibe than not.
=> feat: Svakom Sam and Alex support

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml, buttplug/examples/03-device-enumeration.rs, buttplug/examples/04-device-control.rs, buttplug/src/device/protocol/generic_command_manager.rs, buttplug/src/device/protocol/mod.rs, buttplug/src/device/protocol/svakom_iker.rs, buttplug/src/server/comm_managers/test/mod.rs, buttplug/src/server/comm_managers/test/test_device_comm_manager.rs
=> Svakom support

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml, buttplug/src/device/protocol/lelof1sv2.rs, buttplug/src/device/protocol/libo_elle.rs, buttplug/src/device/protocol/mod.rs
I do wonder if this initializer only change could have been amended
to the original protocol, but this since the initialisation is
distinctly different, it resides in a new protocol.
=> feat: Adding support for the Lelo F1s V2

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml, buttplug/src/device/protocol/satisfyer.rs
Also adding Rise as possible Magic Cell match
=> feat: Adding support for MagicMotion Crystal

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml, buttplug/src/server/device/protocol/lovense.rs, buttplug/src/server/device/protocol/lovense_connect_service.rs
- Added ScalarCmd to Lovense Max in the device configs.
- Incremented the device config minor version.
- Implemented constriction in to the ProtocolHandler for scalar commands.
~ Sutekh
=> Implemented Constriction for Lovense Connect

buttplug/README.md
Update the link to VRPN since they are now using a github.io page.
=> Update link to VRPN

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml
Reported on Discord:
* Fugu2
* Flamingo T
=> feat: Add new Magic Motion identifiers

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml, buttplug/src/server/device/configuration/specifier.rs, buttplug/src/server/device/hardware/communication/hid/hid_comm_manager.rs, buttplug/src/server/device/hardware/communication/hid/hid_device_impl.rs, buttplug/src/server/device/hardware/communication/hid/hidapi_async.rs, buttplug/src/server/device/hardware/communication/hid/mod.rs, buttplug/src/server/device/protocol/fredorch_rotary.rs, buttplug/src/server/device/protocol/magic_motion_v1.rs, buttplug/src/server/device/protocol/mod.rs, buttplug/src/server/device/protocol/nintendo_joycon.rs, buttplug/src/server/device/protocol/svakom_v4.rs
Added:
* Magic Motion Solstice X
* Magic Motion Zenith
* Magic Motion Xone
* Fredorch Rotary devices
=> feat: Protocol updates

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml
Also expanded out Foreo matcher to all vibing products
=> chore: Forgot the bump the device config version

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml, buttplug/src/server/device/hardware/communication/btleplug/btleplug_adapter_task.rs, buttplug/tests/util/device_test/device_test_case/test_foreo_protocol.yaml
Big think in here is that it turns out I had a bad merge that blotted the recent MagicMotion and Fedorch Rotary protocols
Also adding the identifiers for the MysteryVibe *2s, fixing a test and adding reporting for the flaky Actions Semi dongle
=> Protocol work

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml, buttplug/src/server/device/protocol/lovense.rs
Also includes configs for 2 new FunTown devices
=> fix: Undo the write with response change on Lovense identification

buttplug/src/core/message/client_device_message_attributes.rs, buttplug/tests/test_message_downgrades.rs
=> fix: Drop illegal VibrateCmd feature descriptions on protocol downgrade

buttplug/buttplug-device-config/buttplug-device-config.json, buttplug/buttplug-device-config/buttplug-device-config.yml
My Alex Neo 2 appears a bit different.
=> Add alias to Svakom Alex Neo 2

buttplug/buttplug-device-config/build-config/buttplug-device-config-v2.json, buttplug/buttplug-device-config/build-config/buttplug-device-config-v3.json, buttplug/buttplug-device-config/device-config-v2/buttplug-device-config-v2.yml, buttplug/buttplug-device-config/device-config-v3/buttplug-device-config-v3.yml
The device advertises as LVS-Z14 but DeviceType returns FS...
=> fix: Correct the Lovense Mini Sex Machine config

buttplug/buttplug-device-config/build-config/buttplug-device-config-v3.json, buttplug/buttplug-device-config/device-config-v3/buttplug-device-config-v3.yml, buttplug/src/server/device/protocol/kiiroo_keonwifi.rs, buttplug/src/server/device/protocol/mod.rs
Mostly config updates, except for the Keon Wifi shim
=> Protocol work v3 patch
